#Write data
#Sat Sep 20 10:51:12 IST 2025
BaseURL=https\://naveenautomationlabs.com/opencart/index.php?route\=account/register
Email=test1758345672674@gmail.com
Password=ABCD@123
browser=chrome
implicitWait=30
